version: "3.9"
services:
  api-gateway:
    build: .
    ports:
      - "4000:4000"
      - "9229:56745"
    environment:
      NODE_ENV: development
      HOSTNAME: localhost
    volumes:
      - ".:/usr/src/app"
    entrypoint: ["npm", "run", "dev"]