apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-uat
  labels:
      app: api-gateway-uat
      environment: uat
      tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-uat
      environment: uat
  template:
    metadata:
      labels:
        app: api-gateway-uat
        environment: uat
    spec:
      containers:
        - name: api-gateway-uat
          image: docker.lachouquette.ch/api-gateway:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: api-gateway-uat
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-gateway-uat
                  key: REDIS_PASSWORD