apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-uat
  labels:
      app: api-gateway
      environment: uat
      tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      environment: uat
  template:
    metadata:
      labels:
        app: api-gateway
        environment: uat
    spec:
      containers:
        - name: api-gateway-uat
          image: docker.lachouquette.ch/api-gateway:latest
          command: [ "yarn" ]
          args: [ "dev" ]
          ports:
            - name: container-port
              containerPort: 4000
          startupProbe:
            httpGet:
              path: /ready
              port: container-port
            timeoutSeconds: 5
            failureThreshold: 12
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: container-port
            timeoutSeconds: 3
            failureThreshold: 1
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: api-gateway-uat